
const ActionTypes = {
    AppActions: {
        SET_NAV_BAR_VISIBILITY: 'SET_NAV_BAR_VISIBILITY',
    },
    AuthActions: {
        SET_AUTH_CONSTANTS: 'SET_AUTH_CONSTANTS' 
    },
    NavBarActions: {
        SET_TITLE: 'SET_TITLE',
        SET_ACTIVE_TAB: 'SET_ACTIVE_TAB'
    },
    LoginActions: {
        SET_EMAIL_HELP_TEXT: 'SET_EMAIL_HELP_TEXT',
        SET_PASSWORD_HELP_TEXT: 'SET_PASSWORD_HELP_TEXT',
        SET_PASSWORD_VALIDATION_STATE: 'SET_PASSWORD_VALIDATION_STATE',
        SET_EMAIL_VALIDATION_STATE: 'SET_EMAIL_VALIDATION_STATE',
        SET_PROFILE_PIC: 'SET_PROFILE_PIC'
    }
}

export default ActionTypes;